export const RECOMMEND_DATA = 'RECOMMEND_DATA';//首页推荐数据
export const FETCH_CART_LOGIN = 'FETCH_CART_LOGIN';//登录
export const FETCH_USERINFO = 'FETCH_USERINFO';//用户信息
export const GET_SWIPER_IMG = 'GET_SWIPER_IMG';//轮播
export const GET_HOME_NAVS = 'GET_HOME_NAVS';//首页导航
export const FETCH_REG = "FETCH_REG";//注册
export const FETCH_OUT = "FETCH_OUT";//退出
export const GET_HOME_RECOMMEND = 'GET_HOME_RECOMMEND';//首页推荐
export const SEARCH_HOT_RECOMMEND = 'SEARCH_HOT_RECOMMEND';//搜索热门推荐
export const GET_KEY_GOODS = 'GET_KEY_GOODS'; //搜索关键词商品
export const FETCH_GOODS_LEFT = 'FETCH_GOODS_LEFT';//分类左侧
export const FETCH_GOODS_RIGHT = 'FETCH_GOODS_RIGHT';//分类右侧
