export const FETCH_CART_LOGIN = 'FETCH_CART_LOGIN';
export const GET_SWIPER_IMG = 'GET_SWIPER_IMG';
export const GET_HOME_NAVS = 'GET_HOME_NAVS';
export const RECOMMEND_DATA = 'RECOMMEND_DATA'
export const FETCH_REG = "FETCH_REG";
export const GET_HOME_RECOMMEND = 'GET_HOME_RECOMMEND'
